### ISSUE TITLE
compound keywords incorrectly tokenized

### ISSUE THREAD

**Issue by pfitzseb** [JuliaLang/Tokenize.jl#136]
Parts of compound keywords (e.g. `type` or `mutable`) are incorrectly tokenized as `keywords` when they occur on their own:
```
julia> collect(Tokenize.tokenize("type = 3"))
6-element Array{Tokenize.Tokens.Token,1}:
 1,1-1,4          KEYWORD        "type"
 1,5-1,5          WHITESPACE     " "
 1,6-1,6          OP             "="
 1,7-1,7          WHITESPACE     " "
 1,8-1,8          INTEGER        "3"
 1,9-1,8          ENDMARKER      ""

julia> collect(Tokenize.tokenize("mutable = 3"))
6-element Array{Tokenize.Tokens.Token,1}:
 1,1-1,7          KEYWORD        "mutable"
 1,8-1,8          WHITESPACE     " "
 1,9-1,9          OP             "="
 1,10-1,10        WHITESPACE     " "
 1,11-1,11        INTEGER        "3"
 1,12-1,11        ENDMARKER      ""
```

**Comment by c42f** [comment]
This is tricky:
* For efficiency and correct layering, a parser doesn't want to inspect the string representation of tokens, it wants to rely on the kind of contextual keywords being presented to it.
* Figuring out whether these are identifiers or keywords is better left to the parser layer (considering cases like `outer` as well). When the parser figures it out, it can remap the kind of the token to be an identifier in the output.

Therefore I think that keeping these as keywords is a good thing. It could be useful to introduce a `CONTEXTUAL_KEYWORD` as a sub-category of the keywords, though I'm not sure.

BTW, there's at least one surprising contextual keyword `doc` which isn't handled by Tokenize — the presence of `doc` triggers special parsing in the following cases, even though it's otherwise treated as an identifier.

```julia
@doc "docstring"
thing_to_doc
```

```julia
@Mod.doc "docstring"
thing_to_doc
```

**Comment by pfitzseb** [comment]
Agreed. `CONTEXTUAL_KEYWORD` is a nice idea, but not sure whether it's gonna make a big difference (it might, because you can elide the value check in many cases).

**Comment by KristofferC** [comment]
Yeah, I think it is fine to tokenize these as keywords. The parser can always "downcast" these to identifiers, but the other way is annoying.

**Comment by c42f** [comment]
Yeah, this is what `JuliaSyntax.bump(ps, remap_kind=...)` does.
